# Generated by Django 4.2.8 on 2024-01-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_subject_assessment_subject_question_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
