# Generated by Django 4.2.8 on 2024-02-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_assessmentresult_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.option'),
        ),
    ]
