# Generated by Django 4.2.8 on 2024-02-09 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_alter_answer_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 9, 5, 6, 7, 27841, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 5, 6, 7, 21832, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
