# Generated by Django 4.2.8 on 2024-03-10 14:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_assessmentresult_created_at_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 10, 14, 2, 36, 678292, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 14, 2, 36, 678292, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
        migrations.CreateModel(
            name='AudioQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.FileField(upload_to='audio_questions/')),
                ('answer', models.TextField()),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_question', to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_question', to='assessment.content')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_question', to='assessment.subject')),
            ],
        ),
    ]
