# Generated by Django 4.2.8 on 2024-03-12 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_alter_assessmentresult_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='audio_questions',
            field=models.ManyToManyField(related_name='assessment', to='assessment.audioquestion'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
