# Generated by Django 4.2.8 on 2024-03-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_assessment_audio_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='audio_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='audio_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_question', to='assessment.audioquestion'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.question'),
        ),
        migrations.AlterField(
            model_name='audioquestion',
            name='question',
            field=models.FileField(upload_to='audio_questions'),
        ),
    ]
