# Generated by Django 4.2.8 on 2024-03-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_answer_audio_answer_answer_audio_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Cold Storage', 'Cold Storage')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='audioquestion',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Cold Storage', 'Cold Storage')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Cold Storage', 'Cold Storage')], default='Beginner', max_length=20),
        ),
    ]
