# Generated by Django 4.2.8 on 2024-07-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_disability_assessmentresult_disabliity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentresult',
            old_name='disabliity',
            new_name='disabiliity',
        ),
    ]
