# Generated by Django 4.2.8 on 2024-07-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_rename_disabliity_assessmentresult_disabiliity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
