# Generated by Django 4.2.8 on 2024-07-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_alter_assessmentresult_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
