# Generated by Django 4.2.8 on 2024-07-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0015_assessmentresult_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='level',
            field=models.CharField(choices=[('G1L1', 'Group 1 Level 1'), ('G1L2', 'Group 1 Level 2'), ('G2L1', 'Group 2 Level 1'), ('G2L2', 'Group 2 Level 2'), ('G3L1', 'Group 3 Level 1'), ('G3L2', 'Group 3 Level 2'), ('CS', 'Cold Storage')], default='G1L1', max_length=20),
        ),
        migrations.AlterField(
            model_name='audioquestion',
            name='level',
            field=models.CharField(choices=[('G1L1', 'Group 1 Level 1'), ('G1L2', 'Group 1 Level 2'), ('G2L1', 'Group 2 Level 1'), ('G2L2', 'Group 2 Level 2'), ('G3L1', 'Group 3 Level 1'), ('G3L2', 'Group 3 Level 2'), ('CS', 'Cold Storage')], default='G1L1', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('G1L1', 'Group 1 Level 1'), ('G1L2', 'Group 1 Level 2'), ('G2L1', 'Group 2 Level 1'), ('G2L2', 'Group 2 Level 2'), ('G3L1', 'Group 3 Level 1'), ('G3L2', 'Group 3 Level 2'), ('CS', 'Cold Storage')], default='G1L1', max_length=20),
        ),
    ]
