# Generated by Django 4.2.8 on 2025-04-09 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_alter_assessment_level_alter_audioquestion_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('G1L1', 'Group 1 Level 1'), ('G1L2', 'Group 1 Level 2'), ('G2L1', 'Group 2 Level 1'), ('G2L2', 'Group 2 Level 2'), ('G3L1', 'Group 3 Level 1'), ('G3L2', 'Group 3 Level 2'), ('CS', 'Cold Storage')], default='G1L1', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_content', to='assessment.content'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='question_options', to='assessment.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_category', to='assessment.category'),
        ),
    ]
