# Generated by Django 4.2.8 on 2025-05-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_KK_09_04_2025_Add_Category'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='show_correct_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='audio_questions',
            field=models.ManyToManyField(blank=True, related_name='assessment', to='assessment.audioquestion'),
        ),
    ]
