# Generated by Django 4.2.8 on 2025-05-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0018_kk_09_05_2025_add_show_correct_answer_in_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='shuffle_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='level',
            field=models.CharField(choices=[('G1L1', 'Group 1 Level 1'), ('G1L2', 'Group 1 Level 2'), ('G2L1', 'Group 2 Level 1'), ('G2L2', 'Group 2 Level 2'), ('G3L1', 'Group 3 Level 1'), ('G3L2', 'Group 3 Level 2'), ('LS1EIQ1', 'Life Skills 1 EQ 1'), ('LS1MO1', 'Life Skills 1 MO 1'), ('LS1FS1', 'Life Skills 1 FS 1'), ('CS', 'Cold Storage')], default='G1L1', max_length=20),
        ),
        migrations.AlterField(
            model_name='audioquestion',
            name='level',
            field=models.CharField(choices=[('G1L1', 'Group 1 Level 1'), ('G1L2', 'Group 1 Level 2'), ('G2L1', 'Group 2 Level 1'), ('G2L2', 'Group 2 Level 2'), ('G3L1', 'Group 3 Level 1'), ('G3L2', 'Group 3 Level 2'), ('LS1EIQ1', 'Life Skills 1 EQ 1'), ('LS1MO1', 'Life Skills 1 MO 1'), ('LS1FS1', 'Life Skills 1 FS 1'), ('CS', 'Cold Storage')], default='G1L1', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.CharField(choices=[('G1L1', 'Group 1 Level 1'), ('G1L2', 'Group 1 Level 2'), ('G2L1', 'Group 2 Level 1'), ('G2L2', 'Group 2 Level 2'), ('G3L1', 'Group 3 Level 1'), ('G3L2', 'Group 3 Level 2'), ('LS1EIQ1', 'Life Skills 1 EQ 1'), ('LS1MO1', 'Life Skills 1 MO 1'), ('LS1FS1', 'Life Skills 1 FS 1'), ('CS', 'Cold Storage')], default='G1L1', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('G1L1', 'Group 1 Level 1'), ('G1L2', 'Group 1 Level 2'), ('G2L1', 'Group 2 Level 1'), ('G2L2', 'Group 2 Level 2'), ('G3L1', 'Group 3 Level 1'), ('G3L2', 'Group 3 Level 2'), ('LS1EIQ1', 'Life Skills 1 EQ 1'), ('LS1MO1', 'Life Skills 1 MO 1'), ('LS1FS1', 'Life Skills 1 FS 1'), ('CS', 'Cold Storage')], default='G1L1', max_length=20),
        ),
    ]
