# Generated by Django 4.2.8 on 2025-06-23 07:07

import assessment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0019_assessment_shuffle_question_alter_assessment_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresult',
            name='description',
        ),
        migrations.AddField(
            model_name='answer',
            name='fillup_answer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='new_score',
            field=models.JSONField(default=assessment.models.AssessmentResult.default_score),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='audio_questions',
            field=models.ManyToManyField(blank=True, related_name='audio_assessment', to='assessment.audioquestion'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(related_name='text_assessment', to='assessment.question'),
        ),
        migrations.CreateModel(
            name='FillInTheBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('correct_answer', models.JSONField(default=assessment.models.FillInTheBlank.default_correct_answer)),
                ('level', models.CharField(choices=[('G1L1', 'Group 1 Level 1'), ('G1L2', 'Group 1 Level 2'), ('G2L1', 'Group 2 Level 1'), ('G2L2', 'Group 2 Level 2'), ('G3L1', 'Group 3 Level 1'), ('G3L2', 'Group 3 Level 2'), ('LS1EIQ1', 'Life Skills 1 EQ 1'), ('LS1MO1', 'Life Skills 1 MO 1'), ('LS1FS1', 'Life Skills 1 FS 1'), ('CS', 'Cold Storage')], default='G1L1', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fillup_author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fillup_category', to='assessment.category')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fillup_content', to='assessment.content')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fillup_subject', to='assessment.subject')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='fillup_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fillup_question', to='assessment.fillintheblank'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='fillup_questions',
            field=models.ManyToManyField(blank=True, related_name='fillup_assessment', to='assessment.fillintheblank'),
        ),
    ]
