# Generated by Django 4.2.8 on 2025-07-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0020_kk_23_06_2023_addfillup_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='sub_level',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Noun', 'Noun'), ('Pronoun', 'Pronoun'), ('Adjective', 'Adjective'), ('Preposition', 'Preposition'), ('Adverb', 'Adverb'), ('Verb', 'Verb'), ('Conjunct', 'Conjunction'), ('Interject', 'Interjection'), ('Sentences', 'Types of Sentences'), ('ReadComp', 'Reading Comprehension'), ('WriteComp', 'Writing Comprehension'), ('SpeakConv', 'Speaking Conversations'), ('Listening', 'Listening Skills'), ('Tenses', 'Tenses'), ('AntSyn', 'Antonyms & Synonyms'), ('Contract', 'Contractions'), ('OfficeCorr', 'Office Correspondence'), ('Phonics', 'Phonic')], default='General', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='audioquestion',
            name='sub_level',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Noun', 'Noun'), ('Pronoun', 'Pronoun'), ('Adjective', 'Adjective'), ('Preposition', 'Preposition'), ('Adverb', 'Adverb'), ('Verb', 'Verb'), ('Conjunct', 'Conjunction'), ('Interject', 'Interjection'), ('Sentences', 'Types of Sentences'), ('ReadComp', 'Reading Comprehension'), ('WriteComp', 'Writing Comprehension'), ('SpeakConv', 'Speaking Conversations'), ('Listening', 'Listening Skills'), ('Tenses', 'Tenses'), ('AntSyn', 'Antonyms & Synonyms'), ('Contract', 'Contractions'), ('OfficeCorr', 'Office Correspondence'), ('Phonics', 'Phonic')], default='General', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='fillintheblank',
            name='sub_level',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Noun', 'Noun'), ('Pronoun', 'Pronoun'), ('Adjective', 'Adjective'), ('Preposition', 'Preposition'), ('Adverb', 'Adverb'), ('Verb', 'Verb'), ('Conjunct', 'Conjunction'), ('Interject', 'Interjection'), ('Sentences', 'Types of Sentences'), ('ReadComp', 'Reading Comprehension'), ('WriteComp', 'Writing Comprehension'), ('SpeakConv', 'Speaking Conversations'), ('Listening', 'Listening Skills'), ('Tenses', 'Tenses'), ('AntSyn', 'Antonyms & Synonyms'), ('Contract', 'Contractions'), ('OfficeCorr', 'Office Correspondence'), ('Phonics', 'Phonic')], default='General', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='sub_level',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Noun', 'Noun'), ('Pronoun', 'Pronoun'), ('Adjective', 'Adjective'), ('Preposition', 'Preposition'), ('Adverb', 'Adverb'), ('Verb', 'Verb'), ('Conjunct', 'Conjunction'), ('Interject', 'Interjection'), ('Sentences', 'Types of Sentences'), ('ReadComp', 'Reading Comprehension'), ('WriteComp', 'Writing Comprehension'), ('SpeakConv', 'Speaking Conversations'), ('Listening', 'Listening Skills'), ('Tenses', 'Tenses'), ('AntSyn', 'Antonyms & Synonyms'), ('Contract', 'Contractions'), ('OfficeCorr', 'Office Correspondence'), ('Phonics', 'Phonic')], default='General', max_length=40, null=True),
        ),
    ]
