# Generated by Django 4.2.8 on 2025-07-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0021_kk_01_07_2025_add_sublebvel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='level',
            field=models.CharField(choices=[['G1L1', 'Group 1 Level 1'], ['G1L2', 'Group 1 Level 2'], ['G2L1', 'Group 2 Level 1'], ['G2L2', 'Group 2 Level 2'], ['G3L1', 'Group 3 Level 1'], ['G3L2', 'Group 3 Level 2'], ['LS1EIQ1', 'Life Skills 1 EQ 1'], ['LS1MO1', 'Life Skills 1 MO 1'], ['LS1FS1', 'Life Skills 1 FS 1'], ['CS', 'Cold Storage']], default='G1L1', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sub_level',
            field=models.CharField(blank=True, choices=[['General', 'General'], ['Noun', 'Noun'], ['Pronoun', 'Pronoun'], ['Adjective', 'Adjective'], ['Preposition', 'Preposition'], ['Adverb', 'Adverb'], ['Verb', 'Verb'], ['Conjunct', 'Conjunction'], ['Interject', 'Interjection'], ['Sentences', 'Types of Sentences'], ['ReadComp', 'Reading Comprehension'], ['WriteComp', 'Writing Comprehension'], ['SpeakConv', 'Speaking Conversations'], ['Listening', 'Listening Skills'], ['Tenses', 'Tenses'], ['AntSyn', 'Antonyms & Synonyms'], ['Contract', 'Contractions'], ['OfficeCorr', 'Office Correspondence'], ['Phonics', 'Phonics']], default='General', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='audioquestion',
            name='level',
            field=models.CharField(choices=[['G1L1', 'Group 1 Level 1'], ['G1L2', 'Group 1 Level 2'], ['G2L1', 'Group 2 Level 1'], ['G2L2', 'Group 2 Level 2'], ['G3L1', 'Group 3 Level 1'], ['G3L2', 'Group 3 Level 2'], ['LS1EIQ1', 'Life Skills 1 EQ 1'], ['LS1MO1', 'Life Skills 1 MO 1'], ['LS1FS1', 'Life Skills 1 FS 1'], ['CS', 'Cold Storage']], default='G1L1', max_length=20),
        ),
        migrations.AlterField(
            model_name='audioquestion',
            name='sub_level',
            field=models.CharField(blank=True, choices=[['General', 'General'], ['Noun', 'Noun'], ['Pronoun', 'Pronoun'], ['Adjective', 'Adjective'], ['Preposition', 'Preposition'], ['Adverb', 'Adverb'], ['Verb', 'Verb'], ['Conjunct', 'Conjunction'], ['Interject', 'Interjection'], ['Sentences', 'Types of Sentences'], ['ReadComp', 'Reading Comprehension'], ['WriteComp', 'Writing Comprehension'], ['SpeakConv', 'Speaking Conversations'], ['Listening', 'Listening Skills'], ['Tenses', 'Tenses'], ['AntSyn', 'Antonyms & Synonyms'], ['Contract', 'Contractions'], ['OfficeCorr', 'Office Correspondence'], ['Phonics', 'Phonics']], default='General', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='fillintheblank',
            name='category',
            field=models.CharField(blank=True, choices=[('SA', 'Self awareness'), ('EP', 'Empathy'), ('ME', 'Managing emotions'), ('MO', 'Motivating oneself'), ('SS', 'Social Skill'), ('DM', 'Dismissing'), ('DAP', 'Disapproving'), ('LF', 'Laissez Faire'), ('EC', 'Emotion Coaching'), ('PmB', 'PmB'), ('PmG', 'PmG'), ('PvB', 'PvB'), ('PvG', 'PvG'), ('PsB', 'PsB'), ('PsG', 'PsG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fillintheblank',
            name='level',
            field=models.CharField(choices=[['G1L1', 'Group 1 Level 1'], ['G1L2', 'Group 1 Level 2'], ['G2L1', 'Group 2 Level 1'], ['G2L2', 'Group 2 Level 2'], ['G3L1', 'Group 3 Level 1'], ['G3L2', 'Group 3 Level 2'], ['LS1EIQ1', 'Life Skills 1 EQ 1'], ['LS1MO1', 'Life Skills 1 MO 1'], ['LS1FS1', 'Life Skills 1 FS 1'], ['CS', 'Cold Storage']], default='G1L1', max_length=20),
        ),
        migrations.AlterField(
            model_name='fillintheblank',
            name='sub_level',
            field=models.CharField(blank=True, choices=[['General', 'General'], ['Noun', 'Noun'], ['Pronoun', 'Pronoun'], ['Adjective', 'Adjective'], ['Preposition', 'Preposition'], ['Adverb', 'Adverb'], ['Verb', 'Verb'], ['Conjunct', 'Conjunction'], ['Interject', 'Interjection'], ['Sentences', 'Types of Sentences'], ['ReadComp', 'Reading Comprehension'], ['WriteComp', 'Writing Comprehension'], ['SpeakConv', 'Speaking Conversations'], ['Listening', 'Listening Skills'], ['Tenses', 'Tenses'], ['AntSyn', 'Antonyms & Synonyms'], ['Contract', 'Contractions'], ['OfficeCorr', 'Office Correspondence'], ['Phonics', 'Phonics']], default='General', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('SA', 'Self awareness'), ('EP', 'Empathy'), ('ME', 'Managing emotions'), ('MO', 'Motivating oneself'), ('SS', 'Social Skill'), ('DM', 'Dismissing'), ('DAP', 'Disapproving'), ('LF', 'Laissez Faire'), ('EC', 'Emotion Coaching'), ('PmB', 'PmB'), ('PmG', 'PmG'), ('PvB', 'PvB'), ('PvG', 'PvG'), ('PsB', 'PsB'), ('PsG', 'PsG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[['G1L1', 'Group 1 Level 1'], ['G1L2', 'Group 1 Level 2'], ['G2L1', 'Group 2 Level 1'], ['G2L2', 'Group 2 Level 2'], ['G3L1', 'Group 3 Level 1'], ['G3L2', 'Group 3 Level 2'], ['LS1EIQ1', 'Life Skills 1 EQ 1'], ['LS1MO1', 'Life Skills 1 MO 1'], ['LS1FS1', 'Life Skills 1 FS 1'], ['CS', 'Cold Storage']], default='G1L1', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_level',
            field=models.CharField(blank=True, choices=[['General', 'General'], ['Noun', 'Noun'], ['Pronoun', 'Pronoun'], ['Adjective', 'Adjective'], ['Preposition', 'Preposition'], ['Adverb', 'Adverb'], ['Verb', 'Verb'], ['Conjunct', 'Conjunction'], ['Interject', 'Interjection'], ['Sentences', 'Types of Sentences'], ['ReadComp', 'Reading Comprehension'], ['WriteComp', 'Writing Comprehension'], ['SpeakConv', 'Speaking Conversations'], ['Listening', 'Listening Skills'], ['Tenses', 'Tenses'], ['AntSyn', 'Antonyms & Synonyms'], ['Contract', 'Contractions'], ['OfficeCorr', 'Office Correspondence'], ['Phonics', 'Phonics']], default='General', max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
