# Generated by Django 4.2.8 on 2025-07-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0022_KK_17_07_2025_add_category_textchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='subject',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('LF', 'Life Skill')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='audioquestion',
            name='subject',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('LF', 'Life Skill')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fillintheblank',
            name='subject',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('LF', 'Life Skill')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('LF', 'Life Skill')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
