# Generated by Django 4.2.8 on 2025-07-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0023_KK_17_07_2025_subject_textchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='mark_obtained',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='audioquestion',
            name='answer',
            field=models.CharField(max_length=255),
        )
    ]
