# Generated by Django 4.2.8 on 2025-08-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0024_KK_24_07_2025_add_mark_obtained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='mark_obtained',
            field=models.FloatField(blank=True, default=0, null=True),
        )
    ]
