# Generated by Django 4.2.8 on 2026-04-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0027_KK_09_09_2023_add_row_sql'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('assessment_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=40)),
                ('payload', models.JSONField()),
                ('result_id', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['job_id'], name='idx_assessment_job_id'), models.Index(fields=['assessment_id', 'email'], name='idx_assessment_email'), models.Index(fields=['status'], name='idx_assessment_status')],
            },
        ),
    ]
